export const portfolioData = {
  personal: {
    name: "Ryedonna Epin",
    title: "Frontend Developer & UI/UX Enthusiast",
    subtitle: "Crafting beautiful, responsive web experiences with modern technologies",
    email: "ryedonnae@gmail.com",
    linkedin: "https://www.linkedin.com/in/ryedonna-e-103931121/",
    github: "https://github.com/ryedonna",
    profileImage: "/images/profile.webp",
  },
  about: {
    description: [
      "I started my career as an intern in 2020, learning the fundamentals of frontend development, account relationship manager, and customer support. Over the past 4+ years, I&rsquo;ve grown from handling data entry and basic troubleshooting to developing complex frontend applications and leading interface redesigns.",
      "My journey has taken me through customer success, data administration, and now frontend website development. This diverse background gives me a unique perspective on how technology impacts both end-users and business operations.",
      "I understand what users need because I&rsquo;ve been in support roles, and I know how to build it because I&rsquo;ve developed the technical skills along the way. I believe in writing clean, maintainable code and staying up-to-date with the latest industry trends and best practices.",
    ],
  },
  careerJourney: [
    {
      year: "2024-2025",
      role: "Frontend Developer",
      company: "Silkron Technology Sdn Bhd",
      description:
        "Built custom media editor from scratch using Konva.js. Successfully pitched and got approval for complete website redesign. Learned advanced frontend optimization techniques.",
      achievements: [
        "Developed custom media editor with Konva.js",
        "Led website redesign initiative",
        "Improved frontend performance by 40%",
      ],
      technologies: ["React.js", "Konva.js", "Tailwind CSS", "FFMPEG WASM", "Node.js"],
    },
    {
      year: "2023-2024",
      role: "Account Manager & Data Admin",
      company: "Wokok Ready Mix Sdn Bhd",
      description:
        "Bridged technology and business operations. Developed Excel automation tools and built first business website. Gained valuable experience in client management.",
      achievements: [
        "Built company&rsquo;s first business website",
        "Created Excel automation tools",
        "Managed key client relationships",
      ],
      technologies: [
        "Excel",
        "Google Sites",
        "Google Workspace",
        "OneDrive Backup Solution",
        "Google Domain/Squarespace",
      ],
    },
    {
      year: "2021-2023",
      role: "Bachelor of Computer Science (Software Engineering) (Hons) - First Class",
      company: "Universiti Tenaga Nasional (UNITEN)",
      description:
        "Completed my bachelor’s degree while deepening knowledge in software engineering, frontend/backend development, and data management. During this period, I interned at Digital Systems Malaysia, where I applied my classroom learning to real-world projects.",
      achievements: [
        "Graduated with First Class Honours",
        "Internship as Frontend Developer (2022)",
        "Specialized in software engineering principles",
      ],
      // technologies: ["Java", "C++", "Python", "Vue.js", "SQL"],
      technologies: ["Software Engineering Course (Website and Mobile Application development"],
    },
    {
      year: "2022",
      role: "Intern Frontend Developer",
      company: "Digital Systems Malaysia Sdn Bhd",
      description:
        "Developed and maintained frontend components using Vue.js. Contributed to ongoing projects and learned professional development practices.",
      achievements: [
        "Contributed to ongoing client projects",
        "Learned Vue.js framework",
        "Implemented responsive designs",
      ],
      technologies: ["Vue.js", "JavaScript", "DevOps", "CSS"],
    },
    {
      year: "2018-2021",
      role: "Diploma in Computer Science - First Class",
      company: "Universiti Tenaga Nasional (UNITEN)",
      description:
        "Laid my academic foundation in programming, database systems, and software development. Balanced coursework while gaining early career exposure at TrackerHero.",
      achievements: [
        "Graduated with First Class Honours",
        "Built strong foundation in CS fundamentals",
        "Started professional journey in 2020 at TrackerHero",
      ],
      // technologies: ["C", "Java", "SQL", "HTML", "CSS", "JavaScript"],
      technologies: ["Diploma Computer Science Course"],
    },
    {
      year: "2020",
      role: "Account Relationship Manager, Customer Success & Support, Operation, and Intern Frontend Developer",
      company: "TrackerHero",
      description:
        "Started my career with data entry, customer support, and basic frontend development, where I developed strong problem-solving skills and user empathy. Later, I was promoted to Account Relationship Manager, where I managed all Telekom Malaysia security vendor accounts in Sabah and Sarawak, along with several from other states. In this role, I supported more than 50 vendors in adopting our smart patrolling system, provided training and technical assistance, and ensured that hundreds of reports were accurately delivered to Telekom Malaysia.",
      achievements: [
        "Handled 200+ customer inquiries monthly",
        "Improved customer satisfaction by 25%",
        "Learned basic frontend development",
      ],
      technologies: [
        "Vue.js",
        "Laravel Php",
        "MySQL",
        "Mysql Workbench",
        "Customer Support",
        "MDM Remote Control Support",
      ],
    },
  ],
  skills: [
    {
      icon: "💻",
      title: "Core Frontend Skills",
      gradient: "from-blue-600 to-purple-600",
      skills: [
        "React.js",
        "Next.js",
        "Vue.js",
        "JavaScript",
        "TypeScript",
        "HTML5",
        "CSS3",
        "SASS",
        "Tailwind CSS",
        "Bootstrap",
        "Material-UI",
        "Styled Components",
        "UI/UX Design",
        "Responsive Web Design",
        "Konva.js",
        "FFMPEG WASM",
      ],
    },
    {
      icon: "🗄️",
      title: "Backend & Database",
      gradient: "from-rose-500 to-pink-600",
      skills: [
        "Laravel",
        "PHP",
        "MySQL",
        "SQL",
        "API Integration",
        "Web Application Development",
        "Performance Optimization",
      ],
    },
    {
      icon: "🛠️",
      title: "Tools & Collaboration",
      gradient: "from-emerald-600 to-teal-600",
      skills: [
        "Git",
        "SVN",
        "MySQL Workbench",
        "phpMyAdmin",
        "SQLyog",
        "Microsoft Excel (Automation)",
        "Microsoft Office",
        "Google Workspace / Admin / Domain / Sites",
        "Trello",
        "TeamViewer",
        "Canva",
      ],
    },
    {
      icon: "🤝",
      title: "Soft Skills",
      gradient: "from-yellow-500 to-amber-600",
      skills: [
        "Project Coordination",
        "Client Management",
        "Problem Solving",
        "Cross-Browser Testing",
        "Attention to Detail",
        "Team Leadership",
        "Collaboration",
        "Customer Support",
      ],
    },
    {
      icon: "🌱",
      title: "Currently Learning",
      gradient: "from-orange-500 to-red-500",
      skills: [
        "Advanced React Patterns",
        "Modern CSS Techniques",
        "Backend Integration",
        "Mobile-First Development",
        "Improving Mandarin",
      ],
    },
  ],
  projects: [
    {
      title: "Personal Portfolio Website",
      description:
        "A modern, responsive portfolio website built with Next.js 14 and TypeScript. Features a clean design with smooth animations, optimized images, contact form, and showcases projects and skills. Deployed with modern web development best practices.",
      icon: "💼",
      technologies: ["Next.js 14", "TypeScript", "Tailwind CSS", "React", "Vercel"],
      liveUrl: "https://portfolio-ryedonnas-projects.vercel.app/",
      githubUrl: "#",
      image: "/images/project-portfolio.jpg",
    },
    {
      title: "Aeon Bank Assessment Project",
      description:
        "A Next.js application demonstrating a responsive navbar, a secure multi-step login flow with password encryption, and a transaction history dashboard. Features SHA-256 password hashing, mock API endpoints, and responsive UI with Tailwind CSS.",
      icon: "🏦",
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Web Crypto API"],
      liveUrl: "https://aeon-bank-assessment.vercel.app/",
      githubUrl: "https://github.com/ryedonna/aeon-bank-assessment",
      image: "/images/project-aeon-bank.jpg",
    },
    {
      title: "Lattice Mobile Developer Assessment",
      description:
        "A React Native + TypeScript mobile app featuring AI-powered chat (Google Gemini integration) with streaming responses, conversation thread management, and an interactive dashboard with customizable widgets and real-time charts.",
      icon: "📱🤖",
      technologies: [
        "React Native",
        "Expo",
        "TypeScript",
        "Google Gemini API",
        "Tailwind (NativeWind)",
      ],
      liveUrl: "#",
      githubUrl: "https://github.com/ryedonna/lattice-assessment",
      image: "/images/project-lattice.jpg",
    },
  ],
};
